### ISSUE TITLE
Error while trying to install Exodus (install sinabs-exodus)

### ISSUE THREAD

**Issue by sunilthapa-in** [synsense/sinabs-exodus#19]
Hello All

While installing sinabs exodus I am getting some error and am unable to make anything of it:

Building wheels for collected packages: blist
 error: subprocess-exited-with-error
  
 × python setup.py bdist_wheel did not run successfully.
 │ exit code: 1
 ╰─> See above for output.
  
 note: This error originates from a subprocess, and is likely not a problem with pip.
 Building wheel for blist (setup.py) ... error
 ERROR: Failed building wheel for blist
 Running setup.py clean for blist
Failed to build blist
ERROR: Could not build wheels for blist, which is required to install pyproject.toml-based projects

Please help.

This is from https://sinabs.readthedocs.io/en/v1.2.10/tutorials/nmnist.html#training-nmnist-for-deployment-on-speck-using-exodus

I am trying to learn about Sinabs and Speck before I start my project on it.
I am working on Google Colab

**Comment by bauerfe** [comment]
Hi @sunilthapa-in and welcome here! 

Since you mention that you are working on a Colab, what type of runtime are you using? For exodus to work properly you need GPU acceleration and a working installation of CUDA. If you are not sure about this you can run
```
!nvidia-smi
```
in a cell of the colab notebook. If it returns something like `nvidia-smi: command not found` then CUDA is not properly installed or the runtime does not have GPU support.

Otherwise if you post the output here, I will try to help you with it.

**Comment by sunilthapa-in** [comment]
> Hi @sunilthapa-in and welcome here!
> 
> Since you mention that you are working on a Colab, what type of runtime are you using? For exodus to work properly you need GPU acceleration and a working installation of CUDA. If you are not sure about this you can run
> 
> ```
> !nvidia-smi
> ```
> 
> in a cell of the colab notebook. If it returns something like `nvidia-smi: command not found` then CUDA is not properly installed or the runtime does not have GPU support.
> 
> Otherwise if you post the output here, I will try to help you with it.

**Comment by sunilthapa-in** [comment]
Thanks a lot for your guiding response, Felix. 

Yes, it indeed is returning command not found. 

Kindly suggest how may I proceed to address this issue. Thanks

**Comment by bauerfe** [comment]
If you want to use Exodus in a Colab, you will have to change to a runtime with GPU support, and ideally CUDA already installed. I think Colab offers these, but not for free. If you have a local machine with nvidia GPU you could also try to run your code there instead of Colab.

Otherwise, since you mention that you are just getting started with Sinabs and Speck, it might make sense to not use Exodus for the moment. Exodus will make your training and inference faster, but apart from that it is not strictly needed. Sinabs offers all the functionalities that you have in Exodus as well.

**Comment by sunilthapa-in** [comment]
Thank You very much, Felix for such a detailed response. I will proceed with Sinabs at present but at the same time try and troubleshoot Exodus on the lines you have suggested so that I well equipped with more tools (I hope my understanding is correct here :)) if a need arises.

Thank You once again.

Warm Regards,
Sunil

**Comment by bauerfe** [comment]
Happy to be of help :)
